name: mr-crack-tip-fem
channels:
  - conda-forge
dependencies:
  - python=3.11.14
  - fenics-dolfinx=0.10.0
  - fenics-basix=0.10.0
  - fenics-ffcx=0.10.1
  - fenics-ufl=2025.2.0
  - mpi4py=4.1.1
  - petsc=3.24.2
  - petsc4py=3.24.2
  - numpy=2.3.5
  - scipy=1.16.3
  - matplotlib-base=3.10.8
